import React from "react";
import Head from "next/head";
import { AppB, Toolb, Typogr, Logo, Containe, Footer } from "./styled";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Dev Store teste Sorte Online</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AppB position="static">
        <Toolb>
          <Logo>DS</Logo>
          <Typogr variant="h5">Dev Store</Typogr>
        </Toolb>
      </AppB>
      <Containe>{children}</Containe>
      <Footer>
        <Typogr>Teste Sorte Online </Typogr>
      </Footer>
    </div>
  );
}
